/*
 * File: app/model/PageModel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Player.model.PageModel', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'pText',
                type: 'auto'
            },
            {
                allowNull: false,
                name: 'isTocEntry',
                type: 'boolean'
            },
            {
                allowNull: false,
                name: 'pageNum',
                type: 'int'
            },
            {
                allowNull: false,
                name: 'total',
                persist: false,
                type: 'int'
            },
            {
                defaultValue: false,
                name: 'restrictedTopicId',
                type: 'auto'
            },
            {
                allowNull: false,
                defaultValue: false,
                name: 'complete',
                type: 'boolean'
            },
            {
                name: 'pType',
                type: 'string'
            },
            {
                name: 'linkID',
                type: 'string'
            },
            {
                name: 'bookmark',
                type: 'string'
            }
        ]
    }
});