/*
 * File: app/model/ScoSetting.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Player.model.ScoSetting', {
    extend: 'Ext.data.Model',
    alias: 'model.scosetting',
    config: {
        fields: [
            {
                defaultValue: 0,
                name: 'projectId',
                type: 'int'
            },
            {
                name: 'narration',
                type: 'boolean'
            },
            {
                name: 'glossary',
                type: 'boolean'
            },
            {
                name: 'exitButton',
                type: 'boolean'
            },
            {
                name: 'pageNumbering',
                type: 'boolean'
            },
            {
                defaultValue: 'none',
                name: 'tracking',
                type: 'string'
            },
            {
                name: 'completion',
                type: 'string'
            },
            {
                name: 'pageComplete',
                type: 'boolean'
            },
            {
                name: 'autoNavigation',
                type: 'boolean'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
			    defaultValue: false,
                name: 'activateTimer',
                type: 'boolean'
            },
            {
			    defaultValue: 10,
                name: 'timerSeconds',
                type: 'int'
            },
            {
                defaultValue: false,
                name: 'persIndex',
                type: 'boolean'
            },
            {
                defaultValue: false,
                name: 'autoHideToc',
                type: 'boolean'
            },
            {
                defaultValue: false,
                name: 'showHelpOnStart',
                type: 'boolean'
            },
            {
                defaultValue: false,
                name: 'showTocFirst',
                type: 'boolean'
            }
        ],
        proxy: {
            type: 'ajax',
            url: 'data/settings.json'
        }
    }
});